accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  chain_id: "local-ci"
  app_state:
    truststore:
      attestationList: []
      global:
        nextId: 1
      identifierTypeList: 
        - description: "Email address"
          index: "1"
          name: "email"
        - description: "Twitter handle"
          index: "2"
          name: "twitter"
        - description: "Facebook handle"
          index: "3"
          name: "facebook"
        - description: "Mobile phone number"
          index: "4"
          name: "mobile"
init:
  app:
    api.enabled-unsafe-cors: "true"