accounts:
  - name: alice
    coins: ["20000000000utrust", "200000000wotgov"]
  - name: bob
    coins: ["10000000000utrust", "100000000wotgov"]
validator:
  name: alice
  staked: "100000000wotgov"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["1000000utrust"]
genesis:
  chain_id: "local"
  app_state:
    truststore:
      attestationList: []
      global:
        nextId: 1
      identifierTypeList: 
        - description: "Email address"
          index: "1"
          name: "email"
        - description: "Twitter handle"
          index: "2"
          name: "twitter"
        - description: "Facebook handle"
          index: "3"
          name: "facebook"
        - description: "Mobile phone number"
          index: "4"
          name: "mobile"
    staking:
      params:
        bond_denom: "wotgov"
    bank:
      denom_metadata:
        - description: "The Web o' Trust gas token"
          name: "Trust"
          symbol: "TRUST"
          base: "utrust"
          display: "trust"
          denom_units:
            - denom: "utrust"
              exponent: 0
            - denom: "trust"
              exponent: 6
        - description: "The Web o' Trust governance token"
          name: "Wotgov"
          symbol: "WOTGOV"
          base: "wotgov"
          display: "wotgov"
          denom_units:
            - denom: "wotgov"
              exponent: 0
init:
  app:
    api.enabled-unsafe-cors: "true"